### ISSUE TITLE
10.1.5 Broke the addon

### ISSUE THREAD

**Issue by RShadowhand** [Nercus/MapPinEnhanced#10]
Adding a nil check to line 753 fixes it:

`if superTrackedQuestID ~= nill and superTrackedQuestID ~= 0 then`

**Comment by Nercus** [comment]
Hey @RShadowhand ,
thanks for reporting the issue. Had some troubles to consistently recreating the problem. Made some small adjustments. That should fix your problem. New version should be up soon.
