### ISSUE TITLE
Lua error: attempt to call method 'Debug' (a nil value)

### ISSUE THREAD

**Issue by Dathwada** [Nercus/MapPinEnhanced#20]
**v3.0 is pretty awesome. Thank you for this addon, I love it.**

**Describe the bug**
I get the LUA error below on login and reload, I play on the german client of the game.

**To Reproduce**
1. Login the game with a character
2. See error

**Expected behavior**

I expect to not get an lua error on login or reload.

**Screenshots**

**Do you have an error log of what happened?** (BugSack&Buggrabber or `/console scriptErrors 1`)

```plaintext
1x ...faceMapPinEnhanced/utils/locales/locales.lua:10: attempt to call method 'Debug' (a nil value)
[string "@MapPinEnhanced/utils/locales/locales.lua"]:10: in function <...faceMapPinEnhanced/utils/locales/locales.lua:8>
[string "@MapPinEnhanced/utils/slash.lua"]:55: in main chunk

Locals:
t = <table> {
}
k = "Help"
v = "Help"
(*temporary) = nil
(*temporary) = <table> {
 CB = <table> {
 }
 nameVersionString = "MapPinEnhanced v3.0.2"
 locale = "deDE"
 isClassic = false
 L = <table> {
 }
 HBD = <table> {
 }
 LDBIcon = <table> {
 }
 LibDeflate = <table> {
 }
 LibSerialize = <table> {
 }
 version = 302
 addonName = "MapPinEnhanced"
 isRetail = true
 HBDP = <table> {
 }
}
(*temporary) = "Missing localization for: Help"
(*temporary) = "attempt to call method 'Debug' (a nil value)"
MapPinEnhanced = <table> {
 CB = <table> {
 }
 nameVersionString = "MapPinEnhanced v3.0.2"
 locale = "deDE"
 isClassic = false
 L = <table> {
 }
 HBD = <table> {
 }
 LDBIcon = <table> {
 }
 LibDeflate = <table> {
 }
 LibSerialize = <table> {
 }
 version = 302
 addonName = "MapPinEnhanced"
 isRetail = true
 HBDP = <table> {
 }
}

```

**Did you try disabling all other addons? (Only MapPinEnhanced enabled)**
Yes, I tried to enable all other addons.

**Was it working in a previous version?**
Yes, in v2.8.2 I didn't got this error. It started with v3.0.0

**Additional context**

**Comment by Nercus** [comment]
oh, interesting. Will push a fix tonight. Just to rule out some causes. You have not cloned it from Git Hub. Just a normal install from CurseForge/Wago addons right?

**Comment by Dathwada** [comment]
Yes, I installed it from CurseForge.

**Comment by bloerwald** [comment]
Can confirm, happens in CurseForge 3.0.2. 

Moving `utils/debug.lua` up before `locales/_imports.xml` in `utils/_imports.xml` fixes the issue.

**Comment by Nercus** [comment]
released a fix. A new version is on the way
