### ISSUE TITLE
Nothing happen when importing

### ISSUE THREAD

**Issue by Raddosik** [Nercus/MapPinEnhanced#23]
**Describe the bug**
Nothing happen when importing

**To Reproduce**
https://imgur.com/a/nXHNMx6

**Expected behavior**
expected imported map pins

**Screenshots**
same imgur link

**Do you have an error log of what happened?** (BugSack&Buggrabber or `/console scriptErrors 1`)
no error

**Did you try disabling all other addons? (Only MapPinEnhanced enabled)**
yes

**Was it working in a previous version?**
-

**Additional context**
-

**Comment by Nercus** [comment]
Thanks for reporting the bug! Please provide the import string. That would help immensely!

**Comment by Raddosik** [comment]
/way #2213 45.50 12.80 Siesbarg (Mastery)
/way #2216 57.28 36.30 Rej the Dying (Mastery)
/way #2216 55.58 47.54 Zara'azj (Mastery)
/way #2216 56.55 35.49 Tej the Undying (Haste)
/way #2216 55.13 36.53 Venom Dahn (Crit)
/way #2213 53.44 15.31 Sallow (Versa)

for me works only imports like /way 50 50 without location id

**Comment by Nercus** [comment]
Thanks for providing the import string. Unfortunately, I'm not able to reproduce it. I tested it with an English, a German, and a Russian game version. Tested it in different zones and as a temporary and an import to a set (and all combinations of these things) No luck! 😞 
Do you have any other information about it so we can figure it out and fix it for you?

**Comment by Raddosik** [comment]
I fixed it. Just delete settings from wtf folder MapPinEnhanced.lua MapPinEnhanced.lua.bak

**Comment by Nercus** [comment]
hm. Ok. Good to here that you have it fixed. If it ever happens again, I would be very thankful if you could provide your old MapPinEnhanced.lua files.

**Comment by Raddosik** [comment]
[MapPinEnhanced.lua.txt](https://github.com/user-attachments/files/16740834/MapPinEnhanced.lua.txt)

**Comment by Raddosik** [comment]
it again stop importing, but now when i paste  example /way #2215 55.1 55.1 this is not work, but /way #2215 55 55 works fine
