### ISSUE TITLE
Random map pins added on when map is opened

### ISSUE THREAD

**Issue by NoShotz** [Nercus/MapPinEnhanced#26]
When I've been in the new areas for the expansion, I have been getting like 5 or so map pins placed whenever I open my map to the full new zone map, I've got no clue why this is happening.

https://streamable.com/emd4ql

**Comment by Nercus** [comment]
Hey there,

that's caused by the addon Plumber (the option to show the bountiful delves). I have not figured out yet what exactly is causing it in Plumber's code. I'm also trying to contact the developer to find a good solution.

**Comment by NoShotz** [comment]
Ahh, strange.

**Comment by Nercus** [comment]
I got back an answer. Should be fixed in Plumber's next update.
