### ISSUE TITLE
Pins linked to chat are incorrect

### ISSUE THREAD

**Issue by KyoukanGG** [Nercus/MapPinEnhanced#3]
When linking a pin to chat, all pins show as the first pin set. Removing all pins and setting a new pin still causes the issue.

Reproduction steps:
- Set a pin (A)
- Set another pin (B)
- Attempt to link the second pin (B) to chat
- Chat pin will be the first pin (A)
- Remove all pins
- Set a new pin (C)
- Attempt to link the new pin (C) to chat
- Chat pin will be the first pin (A)

**Comment by Nercus** [comment]
Thanks for reporting that bug. I was able to reproduce it and I found a fix for that.
With the release of 9.1 several new performance related problems appeared. I'll try to get them fixed asap and will publish a new release including the fix for your problem.
