### ISSUE TITLE
Request: Enhance import of older format waypoints

### ISSUE THREAD

**Issue by Jahfry** [Nercus/MapPinEnhanced#35]
**Is your feature request related to a problem? Please describe.**

Almost thought of this as a bug, but it's more just that MPE isn't quite handling older TomTom formatted waypoints. Request is to better handle region names. 

**Describe the solution you'd like**

I'm not sure how MPE parses the "/way" command, but would like it if all alpha/non-numerics prior to the first numeral were used to determine the zone for a pin. 

Example that WORKS:
"/way Blasted Lands 44.3 87.5"

Example that does not import:
"/way Hinterlands 14.1 44.6"

Variations that *don't* work:
/way The Hinterlands 14.1 44.6
/way "The Hinterlands" 14.1 44.6

**Does** work:
/way #26 14.1 44.6

**Additional context**

This is no big deal in normal day playing, but when doing something like collecting Halloween treats and importing a large list from a WoWHead comment, many times these were done with the zone names. 

I haven't quite wrapped my head around what to do to manually fix some of these without doing a lookup on [all the zone ids](https://www.wowhead.com/guide/list-of-zone-ids-for-navigation-in-wow-and-tomtom-19501). But that becomes pretty harsh when doing hundreds of zones. 

I'm also not sure what the issue is. At first I though it was spaces, but some zones with spaces work, while others don't. 

[Example to pull from for test](https://www.wowhead.com/achievement=966/tricks-and-treats-of-eastern-kingdoms#comments) ... the highest ranked comment with a bunch of waypoints. Only 10 of them properly parse into MPE.

**Comment by Nercus** [comment]
The current implementation of parsing that information is built in a way to be a lot faster than the previous version. The disadvantage of that was, that I had to drop support for zone names. I will try to find a solution for that though, but can't promise anything in the next update as there are a lot of other features with high priority right now :)

**Comment by Nercus** [comment]
A fix will be added in the next version with the release of 11.0.7

**Comment by Nercus** [comment]
New version with the fix is out!

**Comment by lemieszek** [comment]
I found a bug with this line:
```lua
  if (type(tonumber(tokens[idx]) == "number") or string.find(tokens[idx], "%d" .. decimal_separator .. "%d")) then
```

Fixed in:
https://github.com/Nercus/MapPinEnhanced/pull/38
cc: @Nercus
