### ISSUE TITLE
Tracker doesn't show

### ISSUE THREAD

**Issue by WanderingFox** [Nercus/MapPinEnhanced#7]
**Describe the bug**
the tracker frame does not show at all when `/mph tracker` is used. No error is generated.

**To Reproduce**
1. Add several map pins
2. Attempt to toggle the tracker
3. Note that it does not appear visible

**Expected behavior**
tracker should show up

**Did you try disabling all other addons? (Only MapPinEnhanced enabled)**
Yes

**Was it working in a previous version?**
Dunno. Just installed it :)

**Additional context**
Thank you for this addon! I was going to write it myself, but you've beaten me to it. It works great except for the above mentioned issue with the tracker frame. :)

**Comment by WanderingFox** [comment]
Strangely clearing and re-adding some pins made the pin tracker show up, so I have no idea what that was about.

Thanks for the amazing addon!

**Comment by Nercus** [comment]
Hey @WanderingFox,

even though that somehow fixed itself, I already heard from someone else a similar problem. Currently I can't reproduce that and need to dig deeper to find a fix. Please let me know if that issue happens again. If it does please use the following command `/dump MPHFrame` and attach the output. That would help a lot. Cheers 😃
