### ISSUE TITLE
Pintracker order changes upon reaching a pin

### ISSUE THREAD

**Issue by WanderingFox** [Nercus/MapPinEnhanced#8]
**Describe the bug**
When several pins are being tracked, the order changes when one of the pins is auto completed. Specifically, the last pin in the list jumps to the first entry rather than it moving to the second entry in the list.

**To Reproduce**
1. Create several pins an area
2. Select the first pin in the pin tracker
3. Note the coords of the last pin in the tracker
4. Get within 10 yards of the first pin so that it is removed from the tracker
5. Note that the new first pin in the tracker is the last pin in the list

**Expected behavior**
The list should not re-order. When the first entry on the tracker is removed the second entry should become the first entry.

**Screenshots**
![image](https://user-images.githubusercontent.com/2967926/232580192-9c9d29b4-46bf-40b3-b859-140945643d89.png)
3 pins created in a line
![image](https://user-images.githubusercontent.com/2967926/232580297-ab21ec99-6d36-465f-b6b5-5e5a6ae2ace2.png)
After reaching the first pin (note the third pin in the previous picture has become the first pin)

What I expect to happen:
![image](https://user-images.githubusercontent.com/2967926/232580473-17c5b8cc-0f76-4ef7-ada6-8cd8afaee91e.png)

**Do you have an error log of what happened?** (BugSack&Buggrabber or `/console scriptErrors 1`)

No error is generated

**Did you try disabling all other addons? (Only MapPinEnhanced enabled)** Yes

**Was it working in a previous version?** Not sure, just noticed it

**Additional context**
N/A

**Comment by Nercus** [comment]
Hey @WanderingFox 

thanks for providing all the info. I'll put that an my todo list and try to provide a fix in the coming days.

**Comment by Nercus** [comment]
Should be fixed with aa3c8d77fd37cf64895fedaa070cf0bf3d24f27e
