### ISSUE TITLE
Selected pin drops to the bottom when the top pin is reached

### ISSUE THREAD

**Issue by WanderingFox** [Nercus/MapPinEnhanced#9]
**Describe the bug**
Firstly, thanks for fixing the previous bug works great now!

There is one bit of fallout is that the "selected pin" still has the old behavior of picking the thing at the bottom of the list rather than selecting the top item.

**To Reproduce**
Same as in #8 
Create some pins and select the top one, get within 10 yards of it so it is removed from the tracker and note which pin gets highlighted next (it'll be the one at the bottom rather than the one at the top)

**Expected behavior**
Selected pin follows the logical progression of the pins in order (eg if tracking the first pin and it goes away it should swap to the new first pin which is next in the list)

**Screenshots**

**Do you have an error log of what happened?** (BugSack&Buggrabber or `/console scriptErrors 1`)

N/A

**Did you try disabling all other addons? (Only MapPinEnhanced enabled)**

**Was it working in a previous version?**

**Additional context**
Thank you again for fixing the previous bug!

**Comment by WanderingFox** [comment]
additional info: It looks like it only happens if pins are in different maps from each other

**Comment by WanderingFox** [comment]
odd i can't reproduce it now -_-

**Comment by Nercus** [comment]
Even though you closed the issue I still tried to reproduce the same issue. Unfortunately no success.
If you ever encounter the issue again feel free to reopen this issue.

**Comment by Nercus** [comment]
reopen by accident
